import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TinkHack Countdown",
  description: "Generated by Joel K George & ChatGPT",
};

// const satoshi = localFont({
//   src: "./Satoshi-Variable.ttf",
//   variable: "--font-satoshi"
// })

const khuja = localFont({
  src: "./KhujaUppercase-Uppercase.ttf",
  variable: "--font-khuja"
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={khuja.variable}>
      <body className={spaceGrotesk.className}>{children}</body>
    </html>
  );
}
